services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-dwh
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SqlServer@123"
    ports:
      - "1433:1433"
    volumes:
      - ./datasets:/datasets
      - sqlserver_data:/var/opt/mssql
      - ../scripts:/scripts
    restart: unless-stopped

volumes:
  sqlserver_data: